name: Build and Deploy to Dev
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '10.10'
      - name: Install Dependencies
        run: cd functions && npm install
      - name: Build
        run: cd functions && npm run build
      - name: Deploy angular app to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project prod 
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}